spring:
  profiles:
    active: dev
  application:
    name: java-stack-test-task
  datasource:
    schema: classpath:db/schema.sql
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
---
spring:
  profiles: dev
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/java-stack-test-task-db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  flyway:
    schemas: public_flyway
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_POST:5432}/java-stack-test-task-db
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
logging:
  level:
    root: info
    org.springframework.data.r2dbc: debug